#! /bin/sh

killall -q sxhkd
sxhkd &

~/.config/polybar/launch.sh &

bspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color    \#bf00f6
bspc config active_border_color	    \#bf00f6
bspc config normal_border_color	    \#00DCF6
bspc config presel_feedback_color   \#bf00f6

#bspc rule -a Chromium desktop='^2'
bspc rule -a MEGAsync state=floating follow=on
bspc rule -a Java state=floating follow=on
bspc rule -a jetbrains-idea state=floating follow=on
#bspc rule -a vokoscreenNG state=floating follow=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

feh --bg-fill /home/enrique/Pictures/wallpapers/BB/721305.jpg &
#feh --bg-fill /home/enrique/Pictures/wallpapers/Linux/Arch-linux/Arch-linux.jpg &

#----------------------------------------------------------------------
#CUSTOM
#----------------------------------------------------------------------

#Solucionar problemas con aplicaciones Java
#wmname LG3D &

#Tema del cursor
xsetroot -cursor_name left_ptr &

#Iniciar redshift
killall -q redshift
redshift -P -O 4500 &

#Iniciar mega
killall -q megasync
megasync &

#Activar el numpad para usar las flechas y subfunciones
setxkbmap -option "numpad:microsoft"

#Establecer el teclado en ingles internacional con dead keys
setxkbmap -layout us -variant altgr-intl &

#Iniciar los servicios de dunst
#systemctl start --user dunst.service

#setxkbmap -option grp:alt_shift_toggle us,es &
#alsactl restore

killall -q picom
picom --experimental-backends &
#picom --config /home/enrique/.config/picom/picom.conf &
